name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Debug info
      run: |
        pip freeze

    - name: Black
      if: always()
      run: |
        black . --check

    - name: Flake8
      if: always()
      run: |
        flake8 .

    - name: MyPy
      if: always()
      run: |
        mypy .

    - name: PyTest
      if: always()
      run: |
        pytest -v .
